const IDP_CATEGORIES = {
  Trade: [
    'General Dealer',
    'Spaza Shop',
    'Street Vendor',
    'Clothing & Fashion',
    'Electronics',
    'Mobile Airtime & Accessories',
    'Beauty Products',
    'Household Items',
    'Fruit & Vegetable Vendor',
    'Second-hand Goods',
    'Other Trade',
  ],
  'Production/Manufacturing': [
    'Food Production & Processing',
    'Bakery',
    'Beverage Production',
    'Textile & Clothing Manufacturing',
    'Furniture Manufacturing',
    'Crafts & Handicrafts',
    'Metalwork & Welding',
    'Woodwork & Carpentry',
    'Beadwork & Jewelry',
    'Soap & Detergent Making',
    'Other Manufacturing',
  ],
  'Service Provision': [
    'Hair Salon & Barbershop',
    'Beauty & Spa Services',
    'Tailoring & Sewing',
    'Cleaning Services',
    'Laundry & Ironing',
    'Childcare & Daycare',
    'Event Planning',
    'Catering Services',
    'Photography & Videography',
    'Computer & Phone Repair',
    'Car Wash',
    'Construction & Building',
    'Plumbing',
    'Electrical Work',
    'Painting & Decoration',
    'Transport Services (Taxi, Uber)',
    'Delivery Services',
    'Security Services',
    'Other Services',
  ],
  Agriculture: [
    'Crop Farming',
    'Vegetable Gardening',
    'Poultry Farming (Chickens)',
    'Livestock Farming (Cattle, Goats, Sheep)',
    'Piggery',
    'Fish Farming (Aquaculture)',
    'Beekeeping (Honey Production)',
    'Dairy Farming',
    'Nursery & Plant Sales',
    'Other Agriculture',
  ],
  Other: [
    'Digital Services (Web Design, Social Media)',
    'Education & Training',
    'Health & Wellness',
    'Tourism & Hospitality',
    'Entertainment & Arts',
    'Other (Please Specify)',
  ],
};

export default IDP_CATEGORIES;
